apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client-deployment
  namespace: e-store
spec:
  selector:
    matchLabels:
      app: web-client-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: web-client-deployment
    spec:
      containers:
        - name: web-client-container
          image: rso6315/web-client:latest
          ports:
            - containerPort: 80
          env:
            - name: RSO_API_URL
              value: http://34.89.139.199
            - name: RSO_KEYCLOAK_REALM
              value: rso
            - name: RSO_KEYCLOAK_CLIENTID
              value: rso-public
            - name: RSO_KEYCLOAK_URL
              value: https://keycloak.mjamsek.com/auth
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-client
  name: web-client
  namespace: e-store
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31030
      targetPort: 80
      protocol: TCP
  selector:
    app: web-client-deployment
