sudo: required

services:
  - docker

language: node_js
dist: trusty
node_js:
  - '12'

branches:
  only:
    - develop

cache:
  directories:
    - ./node_modules
    - "$HOME/google-cloud-sdk/"

env:
    global:
        - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
        - PROJECT_NAME=local-reference-258619
        - CLUSTER_NAME=third-cluster
        - CLOUDSDK_COMPUTE_ZONE=europe-west3-b
        - DOCKER_IMAGE_NAME=rso6315/web-client
        - KUBE_DEPLOYMENT_NAME=web-client-deployment
        - KUBE_DEPLOYMENT_CONTAINER=web-client-container

install: npm install

script:
  - npm run build:prod
  - docker build -t rso6315/web-client .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push rso6315/web-client

before_deploy:
    - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
    - source /home/travis/google-cloud-sdk/path.bash.inc
    - gcloud --quiet version
    - gcloud --quiet components update
    - gcloud --quiet components update kubectl

deploy:
    - provider: script
      script: bash ./.ci/deploy.sh
      skip_cleanup: true
      on:
          branch: develop

notifications:
  email: false
  slack:
    rooms:
      - rso-6315:GemkjD1zzD1AAKrXCrn9LUC3
    on_success: always
    on_failure: always
    template:
      - "`%{result}` build for repo `%{repository_slug}` on branch `%{branch}`. Build (<%{build_url}|#%{build_number}>). Commit (<%{compare_url}|%{commit}>)."
      - "Execution time: *%{duration}*"
      - "Message: *%{message}*"
